version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - doc-net
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/var/www
    networks:
      - doc-net
  mysql:
    image: mariadb:10
    container_name: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=docker
    networks:
      - doc-net
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - doc-net
  node:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - doc-net

networks:
  doc-net:

volumes:
  mysqldata:
    name: mysqldata
    external: true
  redisdata: